spring :
  datasource:
    url: jdbc:mysql://localhost:3306/citizenservice?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root   #root
    password: WANAparthy@544  #WANAparthy@544
    driver-class-name: com.mysql.cj.jdbc.Driver