server:
  port: 9191
  ssl:
    enabled: false
    # key-store: keystore.p12
    # key-store-password: testtest
    # keyStoreType: PKCS12
    # keyAlias: tomcat
  # servlet:
  #   context-path: /railway

spring:
  profiles:
    active : dev # Change to 'prod' for production environment
  application:
    name: railway-web


  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  cloud:
    gcp:
      project-id: isentropic-road-453704-e4
      credentials:
        location: classpath:isentropic-road-453704-e4-2899351497d5.json
      spanner:
        instance-id: demo-instance
        database: yt-demo
  # database : indian_railway
  datasource:
    url: jdbc:mysql://localhost:3306/indian_railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root   #root
    password: WANAparthy@544  #WANAparthy@544
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      host: localhost
      port: 27017
      database: indian_railway

  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: "K9I+Ytqgl*qRs9cjOD4m"
    connection-timeout: 10s
    socket-timeout: 30s

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23lijiUZuW9s7JxHmd
            client-secret: 68f9530bc5f73149df7917699a6266cf4b39ede3
            scope: read:user
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            authorization-grant-type: authorization_code
            client-name: GitHub
            client-authentication-method: client_secret_basic
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
app:
  passengers:
    default-seat: A1
    global-settings:
      allow-children: true
      max-count: 6
    list:
      - name: Alice
        age: 30
        ticket:
          type: AC
          number: T123
      - name: Bob
        age: 25

# Uncomment and configure if needed:
# spring:
#   cache:
#     type: redis
#   redis:
#     host: localhost
#     port: 6379

# management:
#   security:
#     enabled: false
#   server:
#     port: 9001
#     address: 127.0.0.1
#   endpoints:
#     web:
#       exposure:
#         include: health,info,beans,env

# info:
#   app:
#     name: Spring Actuator Example
#     java:
#       version: 10
#     type: Spring Boot

# yaml

